### ISSUE TITLE
[ERROR] Node.js 18+ incorrect control file information

### ISSUE THREAD

**Issue by theofficialgman** [nodesource/distributions#1492]
**Describe your bug**
This bug has been incorrectly closed months ago (https://github.com/nodesource/distributions/issues/1392#issue-1224997595) and is still unfixed. the control file is incorrect in nodejs18+
```
Package: nodejs
Version: 18.9.1-deb-1nodesource1
Architecture: arm64
Maintainer: Ivan Iguaran <ivan@nodesource.com>
Installed-Size: 174931
Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.2), libstdc++6 (>= 5.2), python3-minimal, ca-certificates
 ```
nodejs 18 depends on much higher than libc6 2.17, libstdc++6 5.2, etc. please fix your pipeline @igsu 
I haven't checked the rpms but I assume they are also similarly broken

**Distribution Information:**
 - OS: all

**Comment by riosje** [comment]
This has been fixed a couple of weeks ago.
now the control file shows glibc1.28 as dependency.

**Comment by theofficialgman** [comment]
@riosje please reopen. the issue is not fully fixed
there should not be a bionic apt repo for nodejs 18/19/+ as the dependencies can not be resolved, yet there still is
https://deb.nodesource.com/node_18.x/dists/bionic/main/binary-arm64/Packages
https://deb.nodesource.com/node_19.x/dists/bionic/main/binary-arm64/Packages

**Comment by riosje** [comment]
Hi @theofficialgman yes you're right, we're working to remove those packages from non supported distros and this will take an extra time, but at this moment at least the control file will fail the installation because the distro doesn't meet the minimum requirements.

**Comment by theofficialgman** [comment]
it has been 2 months and the non-supported distros still have these versions on their repos

**Comment by cobalt2727** [comment]
Looks like we're coming up on the anniversary of [this issue](https://github.com/nodesource/distributions/issues/1392)! How time flies. I guess that means it's actually been about a _year_.
