### ISSUE TITLE
[ERROR] Node.js 20 on debian Bullseye Installation fails due to checksum error

### ISSUE THREAD

**Issue by RebelSoftware** [nodesource/distributions#1576]
When installing Node into docker container an error is received to say that there is a hash failure
```
#0 23.91 E: Failed to fetch https://deb.nodesource.com/node_20.x/dists/bullseye/main/binary-amd64/Packages.gz  File has unexpected size (777 != 776). Mirror sync in progress? [IP: 23.217.103.89 443]
#0 23.91    Hashes of expected file:
#0 23.91     - Filesize:776 [weak]
#0 23.91     - SHA256:b8ca63ac4fbe9dad6950b850a9258db453c68c7b1c60f25457b9709684154e47
#0 23.91     - SHA1:35c0928a4089a3064e90b1c3cd0eb3f90d96983f [weak]
#0 23.91     - MD5Sum:333f082eb4c6371f533f47acb4774153 [weak]
#0 23.91    Release file created at: Tue, 16 May 2023 15:52:17 +0000
```

**Distribution Information:**
 - OS: debian Bullsey 
 - DOCKER php:8.1-cli-bullseye

**Node Version:**
 - Node: 20

**To Reproduce**
Use installation process
```
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
         && apt-get install -y nodejs \
         && npm install --global yarn
```

**Expected behavior**
Node npm and yarn to install into image

**Comment by jaromanda** [comment]
Can confirm this is also an issue with arm64

```
E: Failed to fetch https://deb.nodesource.com/node_20.x/dists/bullseye/main/binary-arm64/Packages.gz  File has unexpected size (773 != 776). Mirror sync in progress? [IP: 2403:5800:100:29::7bfd:9553 443]
   Hashes of expected file:
    - Filesize:776 [weak]
    - SHA256:d7dda878d1a32b5e984eed67f9ce219e91cc688889476a0074ddb2453d72374e
    - SHA1:662c4bc9770a1705f1f19146074fe35f8affa637 [weak]
    - MD5Sum:d3abd4a681e37794d14d09ad3c72c6f0 [weak]
   Release file created at: Tue, 16 May 2023 15:52:17 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

and armhf (not able to copy the output for that)

**Comment by paulzakin** [comment]
Can confirm with on arm64

```
#0 63.49 E: Failed to fetch https://deb.nodesource.com/node_20.x/dists/bullseye/main/binary-arm64/Packages.gz  File has unexpected size (773 != 776). Mirror sync in progress? [IP: 23.220.246.8 443]
#0 63.49    Hashes of expected file:
#0 63.49     - Filesize:776 [weak]
#0 63.49     - SHA256:d7dda878d1a32b5e984eed67f9ce219e91cc688889476a0074ddb2453d72374e
#0 63.49     - SHA1:662c4bc9770a1705f1f19146074fe35f8affa637 [weak]
#0 63.49     - MD5Sum:d3abd4a681e37794d14d09ad3c72c6f0 [weak]
#0 63.49    Release file created at: Tue, 16 May 2023 15:52:17 +0000
#0 63.49 E: Some index files failed to download. They have been ignored, or old ones used instead.
#0 63.50 Error executing command, exiting
```

**Comment by omerinero** [comment]
I'm facing the same problem on Debian (12) Bookworm

```
Err:19 https://deb.nodesource.com/node_20.x bookworm/main amd64 Packages
  File has unexpected size (777 != 776). Mirror sync in progress? [IP: 2a02:26f0:3900::211:c533 443]
  Hashes of expected file:
   - Filesize:776 [weak]
   - SHA256:b8ca63ac4fbe9dad6950b850a9258db453c68c7b1c60f25457b9709684154e47
   - SHA1:35c0928a4089a3064e90b1c3cd0eb3f90d96983f [weak]
   - MD5Sum:333f082eb4c6371f533f47acb4774153 [weak]
  Release file created at: Tue, 16 May 2023 15:52:18 +0000
```

**Comment by LaurensRietveld** [comment]
Interestingly, this doesn't always happen. On one device the following fails (with the mentioned error message), where on other device things work fine.

- Start some docker container: `docker run --rm -it openjdk:11-jre-slim-buster bash`
- Run the following commands:
```bash
apt update && apt install -y curl
curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
apt-get install -y nodejs
```

**Comment by riosje** [comment]
Hi guys we've received some reports about this, I'm checking into this.

**Comment by RebelSoftware** [comment]
> Interestingly, this doesn't always happen. On one device (host with ubuntu 20.04) the following fails with the mentioned error message, where on other device (host with ubuntu 22.04) things work fine.

I think that this is probably a configuration thing. I'd say the system that does not fail is not using the weak file size test, however I haven't been able to discover how to disable the filesize test or even where its implemented :(

The hash tests are more robust.

My guess is the file was edited after hashes were generated.

**Comment by iwebroot** [comment]
Hello,
Same issue.
**OS** : Debian Bullseye 
**architecture** : amd64
```shell
E: Failed to fetch https://deb.nodesource.com/node_20.x/dists/bullseye/main/binary-amd64/Packages.gz  File has unexpected size (776 != 777). Mirror sync in progress? [IP: 2a02:26f0:9100:16::6011:cedb 443]
   Hashes of expected file:
    - Filesize:777 [weak]
    - SHA256:d3f27ebc448d5904f92e83ab311460dbe7f3b1cd301b96e3272ad46f36bedcc5
    - SHA1:d5734eed42a52b07875d413076e72bfc9baf940e [weak]
    - MD5Sum:59e22e9983ba2434a056d4bfeb073938 [weak]
   Release file created at: Thu, 08 Jun 2023 21:03:26 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting
```

**Comment by LaurensRietveld** [comment]
> > Interestingly, this doesn't always happen. On one device (host with ubuntu 20.04) the following fails with the mentioned error message, where on other device (host with ubuntu 22.04) things work fine.
> 
> I think that this is probably a configuration thing. I'd say the system that does not fail is not using the weak file size test, however I haven't been able to discover how to disable the filesize test or even where its implemented :(
> 
> The hash tests are more robust.
> 
> My guess is the file was edited after hashes were generated.

This merely being a (apt?) configuration thing would be strange, given that the MWE uses exactly the same docker image on both devices. (i.e., the configuration inside the docker containers will be exactly the same)
That being said, I have no clue why my snippet fails on some devices and succeeds on others

**Comment by virusproj3ct** [comment]
With this Dockerfile : 
````dockerfile
FROM ubuntu:22.04

# Installation des libs nécessaires
RUN apt update
RUN apt -y install apt-utils curl jq
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
````

I've got the same error when I try to build this image on gitlab CI (without any specific configuration)
````bash
Step 4/19 : RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
 ---> Running in 2a49b933c937
## Installing the NodeSource Node.js 20.x repo...
## Populating apt-get cache...
+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
## Installing packages required for setup: lsb-release gnupg...
+ apt-get install -y lsb-release gnupg > /dev/null 2>&1
## Confirming "jammy" is supported...
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_20.x/dists/jammy/Release'
## Adding the NodeSource signing key to your keyring...
+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null
## Creating apt sources list file for the NodeSource Node.js 20.x repo...
+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x jammy main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x jammy main' >> /etc/apt/sources.list.d/nodesource.list
## Running `apt-get update` for you...
+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:4 https://deb.nodesource.com/node_20.x jammy InRelease [4563 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:6 https://deb.nodesource.com/node_20.x jammy/main amd64 Packages [776 B]
Err:6 https://deb.nodesource.com/node_20.x jammy/main amd64 Packages
  File has unexpected size (777 != 776). Mirror sync in progress? xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  Hashes of expected file:
   - Filesize:776 [weak]
   - SHA256:b8ca63ac4fbe9dad6950b850a9258db453c68c7b1c60f25457b9709684154e47
   - SHA1:35c0928a4089a3064e90b1c3cd0eb3f90d96983f [weak]
   - MD5Sum:333f082eb4c6371f533f47acb4774153 [weak]
  Release file created at: Tue, 16 May 2023 15:52:19 +0000
Fetched 4563 B in 0s (13.6 kB/s)
Reading package lists...
````

**Comment by riosje** [comment]
Hi guys I'm still not able to re-produce this issue so far.

I've purged the cache on the CDN side.

if you access this URL: https://deb.nodesource.com/node_20.x/dists/jammy/main/binary-amd64/Packages
the hashes should match with the following one
```
Size: 30251110
SHA256: 0b32cf05748042caf520d66da41f57bcb7daf715ec2c0a384e02cb6154166af3
SHA1: 36e5878b2c55db12068a1cd93aad00713b2127ae
MD5sum: 560e8346a3499162a1cf004a95bf58c1
```

Also I've validated the checksum of the stored package and it matchs with the served by our CDN.
With this I can be sure there is not corrupted or modified files after the release.
```SHELL
560e8346a3499162a1cf004a95bf58c1  nodejs_20.3.0-1nodesource1_amd64.deb
```

Please run the following commands and try installing it again.
```
ap-get clean
apt-update
```

**Comment by Zenexer** [comment]
Still not fixed, sadly.  InRelease and Release are the broken files, not Packages.

**Comment by Zenexer** [comment]
```
root@e504f25facc0:/# curl -s https://deb.nodesource.com/node_20.x/dists/bullseye/InRelease | grep -e '^Date: ' -e 'main/binary-arm64/Packages\.gz$'
Date: Tue, 16 May 2023 15:52:17 UTC
 d3abd4a681e37794d14d09ad3c72c6f0 776 main/binary-arm64/Packages.gz
 662c4bc9770a1705f1f19146074fe35f8affa637 776 main/binary-arm64/Packages.gz
 d7dda878d1a32b5e984eed67f9ce219e91cc688889476a0074ddb2453d72374e 776 main/binary-arm64/Packages.gz
root@e504f25facc0:/# curl -o Packages.gz https://deb.nodesource.com/node_20.x/dists/bullseye/main/binary-arm64/Packages.gz
root@e504f25facc0:/# curl -so Packages.gz https://deb.nodesource.com/node_20.x/dists/bullseye/main/binary-arm64/Packages.gz
root@e504f25facc0:/# md5sum Packages.gz
dbbb789f45dedfeb0516871e3e3db2c0  Packages.gz
root@e504f25facc0:/# shasum Packages.gz
b3761928b4797f0e8744160c9c0ade1f5d7be8dc  Packages.gz
root@e504f25facc0:/# sha256sum Packages.gz
bcf96163cb941453a04209b1d12b6404589835ee6a283cc0db7620d3524350ad  Packages.gz
```

**Comment by riosje** [comment]
ok, that was useful.
would you mind to try it again in some mins over HTTPS?
thank you

**Comment by iwebroot** [comment]
Thanks, it's work now. 👍

**Comment by omerinero** [comment]
working for me! Thank you

Debian 12

**Comment by dacorsa** [comment]
now it's working, thanks for fix it !!!

**Comment by Blockzilla101** [comment]
i am still having this issue installing on a raspberry pi

```
OK:1 http://ports.ubuntu.com jammy InRelease
OK:2 http://ports.ubuntu.com jammy-security InRelease                                                                      
OK:3 http://ports.ubuntu.com jammy-updates InRelease                                                                                               
OK:4 http://ports.ubuntu.com jammy-backports InRelease                                                                                             
OK:5 http://imola.armbian.com/apt jammy InRelease                                        
Holen:6 https://deb.nodesource.com/node_20.x jammy InRelease [4’563 B]
Holen:7 https://deb.nodesource.com/node_20.x jammy/main arm64 Packages [773 B]
Fehl:7 https://deb.nodesource.com/node_20.x jammy/main arm64 Packages
  Datei hat eine unerwartete Größe (776 != 773). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 2001:1a88:2201::d43c:2512 443]
  Hashes of expected file:
   - Filesize:773 [weak]
   - SHA256:bcf96163cb941453a04209b1d12b6404589835ee6a283cc0db7620d3524350ad
   - SHA1:b3761928b4797f0e8744160c9c0ade1f5d7be8dc [weak]
   - MD5Sum:dbbb789f45dedfeb0516871e3e3db2c0 [weak]
  Release file created at: Thu, 08 Jun 2023 21:03:28 +0000
Es wurden 4’563 B in 3 s geholt (1’486 B/s).
Paketlisten werden gelesen… Fertig
E: Fehlschlag beim Holen von https://deb.nodesource.com/node_20.x/dists/jammy/main/binary-arm64/Packages.gz Datei hat eine unerwartete Größe (776 != 773). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 2001:1a88:2201::d43c:2512 443]
   Hashes of expected file:
    - Filesize:773 [weak]
    - SHA256:bcf96163cb941453a04209b1d12b6404589835ee6a283cc0db7620d3524350ad
    - SHA1:b3761928b4797f0e8744160c9c0ade1f5d7be8dc [weak]
    - MD5Sum:dbbb789f45dedfeb0516871e3e3db2c0 [weak]
   Release file created at: Thu, 08 Jun 2023 21:03:28 +0000
E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
Error executing command, exiting
```

**Comment by Zenexer** [comment]
The issue has indeed returned:

```
% curl -s https://deb.nodesource.com/node_20.x/dists/jammy/main/binary-arm64/Packages.gz\?v=1 | wc -c
     776
% curl -s http://deb.nodesource.com/node_20.x/dists/jammy/main/binary-arm64/Packages.gz\?v=1 | wc -c
     773
```

**Comment by Zenexer** [comment]
This time it looks like the InRelease and Release files are fine, but Packages.gz is out-of-date on HTTPS.  The issue has flipped.

**Comment by riosje** [comment]
I guys, sorry about this issue again, I've forced again the cache purge.
I'll rise a ticket with our CDN vendor.

**Comment by Zenexer** [comment]
Much appreciated!  Let me know if there's any additional debugging info I can provide.

**Comment by RebelSoftware** [comment]
I was able to successfully build the docker image. The CDN issue of serving stale files is a common one, we used to have it all the time when I was dealing with CDN's :(

I am going to be interstate for the next week so won't be able to retry any builds so cant help check the consistency of the solution. 

Thanks @riosje for attending to this.

**Comment by o1y** [comment]
Still having the issue when trying to install `https://deb.nodesource.com/setup_16.x`. Seems the package is invalid.

**Comment by jaromanda** [comment]
Looks like it's working everywhere I need (arm64 bullseye, amd64 bullseye, amd64 bookworm, armhf bullseye) :D

**Comment by Daniere-Mathieu** [comment]
i still got the error with 18 , i got this on raspberry pi
```
pi@raspberrypi:~/pronto $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Get:3 https://deb.nodesource.com/node_18.x bullseye InRelease [4,586 B]
Get:4 https://deb.nodesource.com/node_18.x bullseye/main armhf Packages [786 B]
Err:4 https://deb.nodesource.com/node_18.x bullseye/main armhf Packages
  File has unexpected size (784 != 786). Mirror sync in progress? [IP: 2a02:26f0:b80:5::210:950e 443]
  Hashes of expected file:
   - Filesize:786 [weak]
   - SHA256:494b5f500c74fec4c17e3e453a376ee6bf1a58174f612b214a861a0cb5b61dec
   - SHA1:807d6ad97af66ff09611cf0f93186abddd8502c6 [weak]
   - MD5Sum:a3b3d6e03986d71fedcd168ee692af4a [weak]
  Release file created at: Thu, 13 Apr 2023 14:12:02 +0000
Fetched 4,586 B in 1s (6,396 B/s)
Reading package lists... Done
E: Failed to fetch https://deb.nodesource.com/node_18.x/dists/bullseye/main/binary-armhf/Packages.gz  File has unexpected size (784 != 786). Mirror sync in progress? [IP: 2a02:26f0:b80:5::210:950e 443]
   Hashes of expected file:
    - Filesize:786 [weak]
    - SHA256:494b5f500c74fec4c17e3e453a376ee6bf1a58174f612b214a861a0cb5b61dec
    - SHA1:807d6ad97af66ff09611cf0f93186abddd8502c6 [weak]
    - MD5Sum:a3b3d6e03986d71fedcd168ee692af4a [weak]
   Release file created at: Thu, 13 Apr 2023 14:12:02 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jaromanda** [comment]
Was fixed for 20.3.0

Broken again for 20.3.1

**Comment by NicBeans** [comment]
I am having a similar issue trying to install Nodejs onto a raspberry pi.
OS: Debian GNU/Linux 11 (bullseye) aarch64
Ive tried installing v14(LTS), v17, v18, v19, and v20.
`File has unexpected size (786 != 785). Mirror sync in progress?
`

**Comment by jamesshaw1987** [comment]
Ubuntu 22.04:

```$ apt-get update
[...]
Get:7 http://deb.nodesource.com/node_16.x jammy/main amd64 Packages [776 B]
Err:7 http://deb.nodesource.com/node_16.x jammy/main amd64 Packages
  File has unexpected size (775 != 776). Mirror sync in progress? [IP: xxx.xxx.xxx.xxx]
  Hashes of expected file:
   - Filesize:776 [weak]
   - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6
   - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]
   - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]
  Release file created at: Wed, 19 Apr 2023 16:10:36 +0000
Reading package lists... Done
W: http://deb.nodesource.com/node_16.x/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Failed to fetch http://deb.nodesource.com/node_16.x/dists/jammy/main/binary-amd64/Packages.gz  File has unexpected size (775 != 776). Mirror sync in progress? [IP: xxx.xxx.xxx.xxx]
   Hashes of expected file:
    - Filesize:776 [weak]
    - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6
    - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]
    - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]
   Release file created at: Wed, 19 Apr 2023 16:10:36 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.```

**Comment by SiroAusili** [comment]
Same issue on Ubuntu 22.04 and Docker (Docksal):
```
Err:12 https://deb.nodesource.com/node_16.x bullseye/main amd64 Packages
5.737   File has unexpected size (775 != 776). Mirror sync in progress? [IP: xxx.xx.xxx.xxx]
5.737   Hashes of expected file:
5.737    - Filesize:776 [weak]
5.737    - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6
5.737    - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]
5.737    - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]
5.737   Release file created at: Wed, 19 Apr 2023 16:10:35 +0000
```
8 hours ago it was working

**Comment by elalecs** [comment]
Same issue with node_18.x and node_20.x

```
#0 7.398 E: Failed to fetch https://deb.nodesource.com/node_18.x/dists/jammy/main/binary-arm64/Packages.gz  File has unexpected size (778 != 776). Mirror sync in progress? [IP: 23.203.60.10 443]
#0 7.398    Hashes of expected file:
#0 7.398     - Filesize:776 [weak]
#0 7.398     - SHA256:4cdc71073957aaffbea511d99669cc4fa98b752eab966068a023558555e0ab92
#0 7.398     - SHA1:0b9c08bd020fac9bc1d05b3008fe7aeee3d1a182 [weak]
#0 7.398     - MD5Sum:fc5eace817a48e2a439589628112ec00 [weak]
#0 7.398    Release file created at: Thu, 13 Apr 2023 14:12:05 +0000

```

yesterday was working great

**Comment by rdsun0301** [comment]
^ Same issue, was working a few hours ago.

```
E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (775 != 776). Mirror sync in progress? [IP: 23.216.147.192 443]
--
312 | Hashes of expected file:
313 | - Filesize:776 [weak]
314 | - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6
315 | - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]
316 | - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]
317 | Release file created at: Wed, 19 Apr 2023 16:10:36 +0000
```

**Comment by tersmitten** [comment]
Same here:

```
    virtualbox-iso:     "stderr_lines": [
    virtualbox-iso:         "E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (776 != 775). Mirror sync in progress? [IP: 23.48.23.35 443]",
    virtualbox-iso:         "   Hashes of expected file:",
    virtualbox-iso:         "    - Filesize:775 [weak]",
    virtualbox-iso:         "    - SHA256:0c6d8382f60bbb4bcc24ce922521673cd749c7530b2128b8dffb3e11297d1a15",
    virtualbox-iso:         "    - SHA1:1e1b1951e616fb84373ee32a26944b356a83149d [weak]",
    virtualbox-iso:         "    - MD5Sum:fdee69ee72123acebf6c975c753f6182 [weak]",
    virtualbox-iso:         "   Release file created at: Wed, 21 Jun 2023 21:26:29 +0000",
    virtualbox-iso:         "E: Some index files failed to download. They have been ignored, or old ones used instead."
    virtualbox-iso:     ],
```

**Comment by MatthewEdwards** [comment]
Also seeing the above, same. error and hashes

**Comment by jaytaph** [comment]
same here..  http works, https does not

**Comment by peter-manton** [comment]
Same issue on Debian 10

**Comment by JohnXLivingston** [comment]
Same issue on Debian bullseye, and node 16 LTS:

```
Réception de :5 https://deb.nodesource.com/node_16.x bullseye/main amd64 Packages [775 B]
Err :5 https://deb.nodesource.com/node_16.x bullseye/main amd64 Packages
  Le fichier a une taille incohérente (776 != 775). Le miroir est peut-être en cours de mise à jour ? [IP : 2a02:26f0:9400::215:22bb 443]
  Hashes of expected file:
   - Filesize:775 [weak]
   - SHA256:0c6d8382f60bbb4bcc24ce922521673cd749c7530b2128b8dffb3e11297d1a15
   - SHA1:1e1b1951e616fb84373ee32a26944b356a83149d [weak]
   - MD5Sum:fdee69ee72123acebf6c975c753f6182 [weak]
  Release file created at: Wed, 21 Jun 2023 21:26:27 +0000
```

**Comment by Zenexer** [comment]
@riosje, could you reopen this?

**Comment by jfrej** [comment]
FYI, I'm indirectly affected by this through Playwright which uses nodesource in its Dockerfile: https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.focal#L12

**Comment by npwolf** [comment]
Still affected:
```
E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (775!= 776). Mirror sync in progress? [IP: 23.220.206.29 443]
   Hashes of expected file:
    - Filesize:776 [weak]
    - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6
    - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]
    - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]
   Release file created at: Wed, 19 Apr 2023 16:10:36 +0000
```

**Comment by pixelafk** [comment]
+1

**Comment by kuabhish** [comment]
> Can confirm that it's working now. Thanks!

I am trying to download node - 16. in ubuntu. getting same error.

**Comment by peter-manton** [comment]
Now seems to be working on Node 18 on Debian 10/Buster

**Comment by shadinaif** [comment]
node 16 on ubuntu 20.04, **not** working, same error

**Comment by Francoois** [comment]
Same with node 18 on Ubuntu 22 Jammy
```
E: Impossible de récupérer https://deb.nodesource.com/node_18.x/dists/jammy/main/binary-amd64/Packages.gz  Somme de contrôle de hachage incohére
nte
   Hashes of expected file:
    - Filesize:776 [weak]
    - SHA256:50d8328c928ddd7d3e92a24eaa86582ee700af234efb9be7a5409faca804bdfc
    - SHA1:534fbff39c1182a33ea11c96c3e6b48b4ad7b894 [weak]
    - MD5Sum:367c3d8e7064ca14220fc48b0076bff8 [weak]
   Hashes of received file:
    - SHA256:e920b3bfb51a057ea1957faec3fea2af197a6f6dbfad0bdaf7074c71c1b57595
    - SHA1:e1406d386ef26768a3a5c15d2000b54aa23faf37 [weak]
    - MD5Sum:ec62e16cd333a4c82438580259a719e9 [weak]
    - Filesize:776 [weak]
   Last modification reported: Wed, 21 Jun 2023 21:41:57 +0000
   Release file created at: Thu, 13 Apr 2023 14:12:05 +0000
```

Works with HTTP
`Réception de :6 http://deb.nodesource.com/node_18.x jammy/main amd64 Packages [776 B]`

**Comment by Walter-o** [comment]
`Failed to fetch https://deb.nodesource.com/node_18.x/dists/jammy/main/binary-arm64/Packages.gz  File has unexpected size (778 != 776). Mirror sync in progress? [IP: 84.53.175.42 443]`

ARM64 Ubuntu 22.04 in Docker

**Comment by ecgould04** [comment]
Experiencing the same issue. 
`
#0 13.09 
#0 13.09 ## Running `apt-get update` for you...
#0 13.09 
#0 13.09 + apt-get update
#0 13.55 Get:1 https://deb.nodesource.com/node_18.x focal InRelease [4583 B]
#0 13.72 Get:2 https://deb.nodesource.com/node_18.x focal/main arm64 Packages [776 B]
#0 13.72 Err:2 https://deb.nodesource.com/node_18.x focal/main arm64 Packages
#0 13.72   File has unexpected size (778 != 776). Mirror sync in progress? [IP: 23.34.82.11 443]
#0 13.72   Hashes of expected file:
#0 13.72    - Filesize:776 [weak]
#0 13.72    - SHA256:4cdc71073957aaffbea511d99669cc4fa98b752eab966068a023558555e0ab92
#0 13.72    - SHA1:0b9c08bd020fac9bc1d05b3008fe7aeee3d1a182 [weak]
#0 13.72    - MD5Sum:fc5eace817a48e2a439589628112ec00 [weak]
#0 13.72   Release file created at: Thu, 13 Apr 2023 14:12:04 +0000
#0 13.74 Hit:3 http://ports.ubuntu.com/ubuntu-ports focal InRelease
#0 13.84 Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
#0 13.94 Hit:5 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
#0 14.03 Hit:6 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
#0 14.56 Fetched 4583 B in 1s (3386 B/s)
#0 14.56 Reading package lists...
#0 15.86 E: Failed to fetch https://deb.nodesource.com/node_18.x/dists/focal/main/binary-arm64/Packages.gz  File has unexpected size (778 != 776). Mirror sync in progress? [IP: 23.34.82.11 443]
#0 15.86    Hashes of expected file:
#0 15.86     - Filesize:776 [weak]
#0 15.86     - SHA256:4cdc71073957aaffbea511d99669cc4fa98b752eab966068a023558555e0ab92
#0 15.86     - SHA1:0b9c08bd020fac9bc1d05b3008fe7aeee3d1a182 [weak]
#0 15.86     - MD5Sum:fc5eace817a48e2a439589628112ec00 [weak]
#0 15.86    Release file created at: Thu, 13 Apr 2023 14:12:04 +0000
#0 15.86 E: Some index files failed to download. They have been ignored, or old ones used instead.
#0 15.87 Error executing command, exiting
`

**Comment by m-filippov** [comment]
I have the same problem with amd64 node_16.x
`02:16:36  E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/bullseye/main/binary-amd64/Packages.gz  File has unexpected size (775 != 776). Mirror sync in progress? [IP: 23.213.161.30 443]
02:16:36     Hashes of expected file:
02:16:36      - Filesize:776 [weak]
02:16:36      - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6
02:16:36      - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]
02:16:36      - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]
02:16:36     Release file created at: Wed, 19 Apr 2023 16:10:35 +0000
02:16:36  E: Some index files failed to download. They have been ignored, or old ones used instead.
02:16:36  Error executing command, exiting`

**Comment by kay-ramme** [comment]
any workaround ?

**Comment by kay-ramme** [comment]
switching edge servers seems to help :-)

**Comment by JuanjoEPS** [comment]
Fallo al obtener https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages.gz  El archivo tiene un tamaño inesperado (776 != 775). ¿La sincronización de la réplica está en progreso?

[IP: 130.206.192.15 443]
   Hashes of expected file:
    - Filesize:775 [weak]
    - SHA256:0c6d8382f60bbb4bcc24ce922521673cd749c7530b2128b8dffb3e11297d1a15
    - SHA1:1e1b1951e616fb84373ee32a26944b356a83149d [weak]
    - MD5Sum:fdee69ee72123acebf6c975c753f6182 [weak]
   Release file created at: Wed, 21 Jun 2023 21:26:29 +0000
E: No se han podido descargar algunos archivos de índice, se han omitido, o se han utilizado unos antiguos en su lugar.

**Comment by JuanjoEPS** [comment]
It is solved by editing /etc/apt/sources.list.d/nodesource.list and changing https to http in the URLs, thus:

deb [signed-by=/usr/share/keyrings/nodesource.gpg] http://deb.nodesource.com/node_16.x focal main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] http://deb.nodesource.com/node_16.x focal main

And then typing:

apt update

apt upgrade

**Comment by ambarishsatheesh-rs** [comment]
> It is solved by editing /etc/apt/sources.list.d/nodesource.list and changing https to http in the URLs, thus:
> 
> deb [signed-by=/usr/share/keyrings/nodesource.gpg] http://deb.nodesource.com/node_16.x focal main deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] http://deb.nodesource.com/node_16.x focal main
> 
> And then typing:
> 
> apt update
> 
> apt upgrade

If you're using the install script, something like this works:
`curl -sL https://deb.nodesource.com/setup_16.x | sed 's/https:\/\/deb.nodesource.com/http:\/\/deb.nodesource.com/g' | bash -`
Not very comfortable but better than complete breakage?

**Comment by francoism90** [comment]
I really dislike switching to http.. any workarounds?

Have the same issue with Laravel Sail.

**Comment by natwallbank** [comment]
> I really dislike switching to http.. any workarounds?
> 
> Have the same issue with Laravel Sail.

I ended up using nvm to install node in my Dockerfile, to enable our builds to complete.

**Comment by snakethatlovesstaticlibs** [comment]
I'm also seeing the same issue in our CI

**Comment by shadinaif** [comment]
> node 16 on ubuntu 20.04, **not** working, same error

it's working fine now, no change from my side, no workaround! Maybe it was a caching issue somewhere, I doubt it was my server since I tried clearing the cache

**Comment by abotteram** [comment]
Same problem here. Using the `debian:11-slim` image.

```
#0 1.328 Err:5 https://deb.nodesource.com/node_16.x bullseye/main arm64 Packages
#0 1.328   File has unexpected size (778 != 777). Mirror sync in progress? [IP: 84.53.175.98 443]
#0 1.328   Hashes of expected file:
#0 1.328    - Filesize:777 [weak]
#0 1.328    - SHA256:c6ed70e1806861e1c42fe6f958761189365484a7aa23333e4e42789c487eb4c4
#0 1.328    - SHA1:6dfe05ffd1fd3d20612c3bde25c8c8fb1b481a8f [weak]
#0 1.328    - MD5Sum:36131829d98b2079d9fc77038bbc3328 [weak]
#0 1.328   Release file created at: Wed, 19 Apr 2023 16:10:35 +0000
#0 1.334 Fetched 4586 B in 0s (13.9 kB/s)
#0 1.334 Reading package lists...
#0 1.566 E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/bullseye/main/binary-arm64/Packages.gz  File has unexpected size (778 != 777). Mirror sync in progress? [IP: 84.53.175.98 443]
#0 1.566    Hashes of expected file:
#0 1.566     - Filesize:777 [weak]
#0 1.566     - SHA256:c6ed70e1806861e1c42fe6f958761189365484a7aa23333e4e42789c487eb4c4
#0 1.566     - SHA1:6dfe05ffd1fd3d20612c3bde25c8c8fb1b481a8f [weak]
#0 1.566     - MD5Sum:36131829d98b2079d9fc77038bbc3328 [weak]
#0 1.566    Release file created at: Wed, 19 Apr 2023 16:10:35 +0000
#0 1.566 E: Some index files failed to download. They have been ignored, or old ones used instead.
#0 1.568 Error executing command, exiting
```

**Comment by kay-ramme** [comment]
see above, just switch edge servers, that works as a workaround ..

**Comment by abotteram** [comment]
@kay-ramme 

And how would I go about doing that? I don't know what that means. :)

**Comment by kay-ramme** [comment]
edge servers are mirrors of the origin server, the edge server is typically chosen to be somehow the nearest to your client 
it seems, that some of these edge servers are out of sync with the origin, leading to above reported issue
while others are working properly

different edge servers have different IPs, so, if you have some edge server which is working (you can try e.g. on some remote host or use some other provider), then you use this edge server in the region where you see the error

simplest way was, to just put the IP and the domain name into your /etc/hosts file

e.g. this was working for me

23.216.155.10 deb.nodesource.com

I added it to end of my /etc/hosts

**Comment by Aghassi** [comment]
@JesusPaz Why is this issue closed? Node 16 and other versions that aren't Node 20 are still impacted by this. Can you provide guidance to the community as to what to do to work around this and or when the fix for all versions will be landed?

Our internal CI is currently flakey because of this and we are trying to determine if we keep relying on this package or not as a result.

**Comment by Zenexer** [comment]
It's closed because several people reported that it was resolved across two different issues.  I'm sure they'll reopen it now that people are reporting the fix didn't stick.

**Comment by Zenexer** [comment]
Thanks, @JesusPaz.  As before, let me know if there's any way I can help troubleshoot.

**Comment by elalecs** [comment]
Can someone explain how to force the use of an edge server?

**Comment by Zenexer** [comment]
That's not actually going to fix it.  It might work around it once or twice, but it'll break again.

**Comment by JesusPaz** [comment]
@Aghassi can you include some logs to help us understand what you're experiencing?

**Comment by Aghassi** [comment]
@JesusPaz 

```

[2023-06-26T22:52:50.228Z] #6 10.20 ## Running `apt-get update` for you...

[2023-06-26T22:52:50.228Z] #6 10.20 

[2023-06-26T22:52:50.228Z] #6 10.20 + apt-get update

[2023-06-26T22:52:50.228Z] #6 10.34 Get:1 https://deb.nodesource.com/node_16.x focal InRelease [4583 B]

[2023-06-26T22:52:50.483Z] #6 10.41 Get:2 https://deb.nodesource.com/node_16.x focal/main amd64 Packages [776 B]

[2023-06-26T22:52:50.483Z] #6 10.41 Err:2 https://deb.nodesource.com/node_16.x focal/main amd64 Packages

[2023-06-26T22:52:50.483Z] #6 10.41   File has unexpected size (775 != 776). Mirror sync in progress? [IP: 23.216.147.192 443]

[2023-06-26T22:52:50.483Z] #6 10.41   Hashes of expected file:

[2023-06-26T22:52:50.483Z] #6 10.41    - Filesize:776 [weak]

[2023-06-26T22:52:50.483Z] #6 10.41    - SHA256:e5d3c880cdb1ec15f193329e5a3abe68056c59f6026144de4d4b52fcce2131e6

[2023-06-26T22:52:50.483Z] #6 10.41    - SHA1:87f1583949354fe006bc0137a84d8cfe90b0229d [weak]

[2023-06-26T22:52:50.483Z] #6 10.41    - MD5Sum:c881892f3a46cc943e7ff44162cbee62 [weak]

[2023-06-26T22:52:50.483Z] #6 10.41   Release file created at: Wed, 19 Apr 2023 16:10:36 +0000

[2023-06-26T22:52:50.483Z] #6 10.56 Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease

[2023-06-26T22:52:50.483Z] #6 10.57 Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease

[2023-06-26T22:52:50.738Z] #6 10.71 Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease

[2023-06-26T22:52:50.738Z] #6 10.85 Get:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]

[2023-06-26T22:52:51.299Z] #6 11.36 Fetched 113 kB in 1s (105 kB/s)

[2023-06-26T22:52:52.224Z] #6 11.36 Reading package lists...
```

All we are doing in our dockerfile is 

```
curl -sL https://deb.nodesource.com/setup_16.x | bash -
```

**Comment by lenhartd-apex** [comment]
```
E: Failed to fetch https://deb.nodesource.com/node_16.x/dists/focal/main/binary-arm64/Packages.gz  File has unexpected size (778 != 777). 
Mirror sync in progress?
   Hashes of expected file:
    - Filesize:777 [weak]
    - SHA256:c6ed70e1806861e1c42fe6f958761189365484a7aa23333e4e42789c487eb4c4
    - SHA1:6dfe05ffd1fd3d20612c3bde25c8c8fb1b481a8f [weak]
    - MD5Sum:36131829d98b2079d9fc77038bbc3328 [weak]
   Release file created at: Wed, 19 Apr 2023 16:10:36 +0000
   ```

**Comment by oliverbrancovdexcare** [comment]
Any update on this?

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).

**Comment by jrunestone** [comment]
@JesusPaz I just migrated to the new repo, I'm still getting the same error just now

![image](https://github.com/nodesource/distributions/assets/2293001/d3c5236d-5912-4869-8518-3cb77e12c04b)

**Comment by franee** [comment]
@JesusPaz, thanks for that, I've added some extra notes for Ubuntu on [wiki](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository#debian-configuration-guide).

**Comment by michael-freidgeim-webjet** [comment]
> @JesusPaz, thanks for that, I've added some extra notes for Ubuntu on the [wiki](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository#debian-configuration-guide).
Link to wiki is broken

**Comment by riosje** [comment]
Hi @SturdyStubs would you to open a new issue with your error?
The installation script should not be throwing this error anymore.

**Comment by the-veloper** [comment]
this is still happening. any news?
```
6.603 Fetched 44.3 kB in 2s (22.9 kB/s)
6.603 Reading package lists...
11.20 E: Failed to fetch https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-1nodesource1_amd64.deb  File has unexpected size (27528856 != 27210210). Mirror sync in progress? [IP: 104.22.4.26 443]
11.20    Hashes of expected file:
11.20     - SHA256:80730cbf61c72b9cf55435cdf8bef44a865cd797bdf4b62b7e3a9151568a0a17
11.20     - SHA1:f3ce40f55d97d4582eed117e4d26fdaa09d46a32 [weak]
11.20     - MD5Sum:94cdd9c58e730374a1cf2c818e8ecedb [weak]
11.20     - Filesize:27210210 [weak]
11.20 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by NewEraCracker** [comment]
https://github.com/nodesource/distributions/issues/1576#issuecomment-1698012034
> This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).

Why did you delete that page? Thankfully the WebArchive institution still has it:
https://web.archive.org/web/20231214235502/https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository

https://github.com/nodesource/distributions/issues/1576#issuecomment-2334194944
> this is still happening. any news?

May I suggest: `apt clean && apt update && apt autoremove`
