### ISSUE TITLE
our distribution, identified as "bionic", is not currently supported

### ISSUE THREAD

**Issue by stackoverflow2** [nodesource/distributions#904]
Your distribution, identified as "bionic", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by wolfy1339** [comment]
No longer a problem, this has been fixed.

**Comment by stackoverflow2** [comment]
@wolfy1339  okay.
Thank you.

**Comment by Bugazelle** [comment]
@wolfy1339 

From my end, still not working. I am using the ubuntu:18.04 docker.
Would you please give us a clear step to make it working?

```
root@cd74e0327cff:~# curl -sL -k https://deb.nodesource.com/setup_10.x | bash -

## Installing the NodeSource Node.js 10.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Fetched 252 kB in 10s (26.2 kB/s)
Reading package lists... Done

## Confirming "bionic" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/bionic/Release'

## Your distribution, identified as "bionic", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

root@cd74e0327cff:~#
```

**Comment by wolfy1339** [comment]
Is there any particular reason for installing 10.x ?

They probably don’t support newer distribution versions on the older versions of node that are EOL

________________________________

**Comment by Bugazelle** [comment]
Find the reason, because we are behind the proxy, and the ssl certificate issue, failed to run setup_10.x script.

Suggest:
Add -k in curl command

**Comment by igsu** [comment]
This issue has been fixed, `bionic` is currently supported.
Closing this now.

**Comment by Demasso** [comment]
no it's not.

**Comment by mhedden** [comment]
> ## Confirming "bionic" is supported...
> * curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/bionic/Release'
> 
> ## Your distribution, identified as "bionic", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Hi @Demasso. I had this same problem and found the issue for me was because my corporate proxy does a man in the middle and supplies a self signed certificate that was causing the curl command in the script to fail which is why I got that message. 

So I had to add the self signed corporate root certificate to [ubuntu's ca-certificates](https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line). I also modified the bash script to add --cacert /path/to/selfsigned.crt to the 2 curl commands in the script (ln 281 & ln 303 at time of writing). Although those modifications may not have been necessary after adding the cert to the system but I did it just in case.

After that I was able to install node 13.9.0 without issue. Hopefully this is helpful to anyone who was seeing the same issue and is behind a corporate proxy that inspects and re-signs what is passed through it.

**Comment by donovanmuller** [comment]
I had the same issue with using a corporate proxy but in my case just exporting the `https_proxy` environment variable worked for me:

```console
$ export http_proxy=http://xxx
$ export https_proxy=http://xxx
$ curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
...
```
